import type { GameErrorCode } from "@contracts/errors";
import { ERROR_MESSAGES } from "@contracts/errors";
import type { Language, RejectReason, ScoreReason } from "@contracts/game.schemas";

/**
 * All user-facing copy, in both interface languages (`Plan.md` §2B.9).
 * Category labels are not duplicated here: they come from `CATEGORY_LABELS`
 * in the contracts module. `UI_SR` is the reference: `UI_EN` must have every
 * key, which the `Strings` type enforces.
 */
export const UI_SR = {
  appTitle: "Zanimljiva Geografija Live",
  navLabel: "Glavna navigacija",
  lobbyTitle: "Nova partija",
  displayName: "Tvoje ime",
  createRoom: "Napravi partiju",
  playWithFriend: "Igraj sa prijateljem",
  playWithFriendNote: "Napravi partiju i pošalji kod prijatelju.",
  playWithStranger: "Igraj sa nepoznatim",
  playWithStrangerNote: "Nađi protivnika koji upravo čeka.",
  playWithAi: "Igraj protiv AI",
  playWithAiNote: "AI protivnik igra istu rundu, a njegove odgovore proveravamo isto kao tvoje.",
  languageNote: "Pojmove možeš pisati na srpskom ili na engleskom.",
  aiPrivacyNote:
    "Odgovori i zahtevi za pomoć šalju se AI servisima Google Gemini i Groq radi provere. Ne upisuj lične podatke.",
  searchingTitle: "Tražimo protivnika",
  searchingNote: "Čim se neko pridruži, runda počinje za oboje.",
  cancelSearch: "Odustani od traženja",
  haveCode: "Imaš kod partije?",
  joinInstead: "Pridruži se postojećoj partiji",
  backToLobby: "Nazad na početak",
  leaveGame: "Napusti partiju",
  leaveGameNote: "Kod partije prestaje da važi čim izađeš.",
  roomCode: "Kod partije",
  join: "Pridruži se",
  waitingTitle: "Partija je napravljena",
  waitingForOpponent: "Čekamo drugog igrača. Podeli kod partije.",
  synchronizing: "Oba igrača su tu. Pripremamo rundu…",
  aiRoomTitle: "Igraš protiv AI",
  countdownTitle: "Runda počinje",
  answeringTitle: "Upiši pojmove",
  letterIs: "Slovo",
  timeLeft: "Preostalo vreme",
  finish: "Završio sam",
  finishedTitle: "Tvoji odgovori su zaključani",
  waitingForOpponentFinish: "Čekamo da protivnik završi ili da istekne vreme.",
  opponentFinished: "Protivnik je završio.",
  opponentStillPlaying: "Protivnik još igra.",
  opponentLeft: "Protivnik je napustio partiju. Runda se nastavlja do isteka vremena.",
  aiOpponent: "AI protivnik",
  hint: "Pomoć",
  hintFor: "Pomoć za kategoriju",
  hintsLeft: "Preostalo pomoći",
  hintLoading: "Tražimo pomoć…",
  hintNone: "Za ovo slovo nema poznatog pojma u ovoj kategoriji.",
  hinted: "uz pomoć",
  judgingTitle: "Proveravamo odgovore…",
  judgingNote: "AI proverava da li pojmovi postoje i pripadaju kategoriji. Traje nekoliko sekundi.",
  resultsTitle: "Rezultat",
  you: "Ti",
  opponent: "Protivnik",
  points: "Poeni",
  total: "Ukupno",
  player: "Igrač",
  notScoredYet: "Još nema poena",
  round: "Runda",
  pointsFor: "poena",
  valid: "priznato",
  invalid: "nije priznato",
  noAnswer: "bez odgovora",
  outcomeWin: "Pobedio si!",
  outcomeLoss: "Protivnik je pobedio.",
  outcomeDraw: "Nerešeno.",
  connectionLost: "Veza sa serverom je prekinuta. Osveži stranicu da započneš novu igru.",
  statusEmpty: "prazno",
  statusPending: "čuva se…",
  statusSaved: "sačuvano",
  statusRejected: "nije sačuvano",
  reasons: {
    both_different: "Oba odgovora priznata i različita",
    same_answer: "Isti odgovor",
    only_player_1: "Samo prvi igrač",
    only_player_2: "Samo drugi igrač",
    neither: "Nijedan odgovor nije priznat",
  } satisfies Record<ScoreReason, string>,
  rejectReasons: {
    too_short: "prekratko",
    wrong_letter: "pogrešno slovo",
    not_real: "ne postoji",
    wrong_category: "pogrešna kategorija",
    historical: "ne postoji danas",
    unrecognized: "nije prepoznato",
  } satisfies Record<RejectReason, string>,
  verifiedNote: "Odgovore je proverio AI. Boduje se samo pojam koji postoji i počinje zadatim slovom.",
  unverifiedNote: "AI provera trenutno nije uspela, pa je ova runda bodovana samo po početnom slovu.",
  botFailedNote: "AI protivnik nije uspeo da odgovori u ovoj rundi.",
  theme: "Tema",
  themes: {
    system: "Kao sistem",
    light: "Svetla",
    dark: "Tamna",
  },
  language: "Jezik",
  languages: {
    sr: "Srpski",
    en: "English",
  } satisfies Record<Language, string>,
  errors: ERROR_MESSAGES as Record<GameErrorCode, string>,
};

export type Strings = typeof UI_SR;

export const UI_EN: Strings = {
  appTitle: "Zanimljiva Geografija Live",
  navLabel: "Main navigation",
  lobbyTitle: "New game",
  displayName: "Your name",
  createRoom: "Create game",
  playWithFriend: "Play a friend",
  playWithFriendNote: "Create a game and send the code to a friend.",
  playWithStranger: "Play a random person",
  playWithStrangerNote: "Find an opponent who is waiting right now.",
  playWithAi: "Play against AI",
  playWithAiNote: "The AI opponent plays the same round, and its answers are checked just like yours.",
  languageNote: "You may write answers in Serbian or in English.",
  aiPrivacyNote: "Answers and hint requests are sent to the Google Gemini and Groq AI services to be checked. Don't enter personal data.",
  searchingTitle: "Looking for an opponent",
  searchingNote: "As soon as someone joins, the round starts for both of you.",
  cancelSearch: "Stop looking",
  haveCode: "Have a game code?",
  joinInstead: "Join an existing game",
  backToLobby: "Back to start",
  leaveGame: "Leave game",
  leaveGameNote: "The game code stops working as soon as you leave.",
  roomCode: "Game code",
  join: "Join",
  waitingTitle: "Game created",
  waitingForOpponent: "Waiting for the second player. Share the game code.",
  synchronizing: "Both players are here. Getting the round ready…",
  aiRoomTitle: "You are playing the AI",
  countdownTitle: "Round starts in",
  answeringTitle: "Write your answers",
  letterIs: "Letter",
  timeLeft: "Time left",
  finish: "I'm done",
  finishedTitle: "Your answers are locked",
  waitingForOpponentFinish: "Waiting for your opponent to finish or for time to run out.",
  opponentFinished: "Your opponent has finished.",
  opponentStillPlaying: "Your opponent is still playing.",
  opponentLeft: "Your opponent left the game. The round continues until time runs out.",
  aiOpponent: "AI opponent",
  hint: "Hint",
  hintFor: "Hint for",
  hintsLeft: "Hints left",
  hintLoading: "Getting a hint…",
  hintNone: "There is no well-known term for this letter in this category.",
  hinted: "with a hint",
  judgingTitle: "Checking answers…",
  judgingNote: "The AI is checking that each term exists and fits its category. This takes a few seconds.",
  resultsTitle: "Result",
  you: "You",
  opponent: "Opponent",
  points: "Points",
  total: "Total",
  player: "Player",
  notScoredYet: "No points yet",
  round: "Round",
  pointsFor: "points",
  valid: "accepted",
  invalid: "not accepted",
  noAnswer: "no answer",
  outcomeWin: "You won!",
  outcomeLoss: "Your opponent won.",
  outcomeDraw: "It's a draw.",
  connectionLost: "The connection to the server was lost. Refresh the page to start a new game.",
  statusEmpty: "empty",
  statusPending: "saving…",
  statusSaved: "saved",
  statusRejected: "not saved",
  reasons: {
    both_different: "Both accepted and different",
    same_answer: "Same answer",
    only_player_1: "First player only",
    only_player_2: "Second player only",
    neither: "Neither answer accepted",
  },
  rejectReasons: {
    too_short: "too short",
    wrong_letter: "wrong letter",
    not_real: "doesn't exist",
    wrong_category: "wrong category",
    historical: "no longer exists",
    unrecognized: "not recognized",
  },
  verifiedNote: "Answers were checked by AI. Only a real term that starts with the letter scores.",
  unverifiedNote: "The AI check failed this time, so this round was scored on the starting letter only.",
  botFailedNote: "The AI opponent could not answer this round.",
  theme: "Theme",
  themes: {
    system: "System",
    light: "Light",
    dark: "Dark",
  },
  language: "Language",
  languages: {
    sr: "Srpski",
    en: "English",
  },
  errors: {
    INVALID_PAYLOAD: "The request is not valid.",
    ROOM_NOT_FOUND: "Game not found. Check the code.",
    ROOM_FULL: "That game already has two players.",
    NOT_IN_ROOM: "You are not in this game.",
    WRONG_PHASE: "You can't do that right now.",
    ROUND_STALE: "That round is already over.",
    TOO_EARLY: "The round hasn't started yet.",
    TOO_LATE: "Time is up.",
    ALREADY_FINISHED: "Your answers are already locked.",
    STALE_REVISION: "A newer answer is already saved.",
    RATE_LIMITED: "Too many requests. Try again later.",
    AI_UNAVAILABLE: "The AI is not available right now. Try again a little later.",
    AI_LIMIT: "Today's AI limit is used up. Try again tomorrow.",
    HINT_LIMIT: "No more hints for this category or round.",
    INTERNAL: "Something went wrong.",
  },
};

export const STRINGS: Record<Language, Strings> = { sr: UI_SR, en: UI_EN };
