/**
 * All user-facing copy in one place. Category labels are not duplicated here:
 * they come from `CATEGORY_LABELS_SR` in the contracts module.
 */
export const UI_SR = {
  appTitle: "Zanimljiva Geografija Live",
  navLabel: "Glavna navigacija",
  lobbyTitle: "Nova partija",
  displayName: "Tvoje ime",
  createRoom: "Napravi partiju",
  playWithFriend: "Igraj sa prijateljem",
  playWithFriendNote: "Napravi partiju i pošalji kod prijatelju.",
  playWithStranger: "Igraj sa nepoznatim",
  playWithStrangerNote: "Nađi protivnika koji upravo čeka.",
  searchingTitle: "Tražimo protivnika",
  searchingNote: "Čim se neko pridruži, runda počinje za oboje.",
  cancelSearch: "Odustani od traženja",
  playingAs: "Igraš kao",
  haveCode: "Imaš kod partije?",
  joinInstead: "Pridruži se postojećoj partiji",
  backToLobby: "Nazad na početak",
  roomCode: "Kod partije",
  join: "Pridruži se",
  waitingTitle: "Partija je napravljena",
  waitingForOpponent: "Čekamo drugog igrača. Podeli kod partije.",
  synchronizing: "Oba igrača su tu. Pripremamo rundu…",
  countdownTitle: "Runda počinje",
  answeringTitle: "Upiši pojmove",
  letterIs: "Slovo",
  timeLeft: "Preostalo vreme",
  finish: "Završio sam",
  finishedTitle: "Tvoji odgovori su zaključani",
  waitingForOpponentFinish: "Čekamo da protivnik završi ili da istekne vreme.",
  opponentFinished: "Protivnik je završio.",
  opponentStillPlaying: "Protivnik još igra.",
  resultsTitle: "Rezultat",
  you: "Ti",
  opponent: "Protivnik",
  points: "Poeni",
  total: "Ukupno",
  player: "Igrač",
  notScoredYet: "Još nema poena",
  round: "Runda",
  pointsFor: "poena",
  valid: "priznato",
  invalid: "nije priznato",
  noAnswer: "bez odgovora",
  outcomeWin: "Pobedio si!",
  outcomeLoss: "Protivnik je pobedio.",
  outcomeDraw: "Nerešeno.",
  connectionLost: "Veza sa serverom je prekinuta. Osveži stranicu da započneš novu igru.",
  statusEmpty: "prazno",
  statusPending: "čuva se…",
  statusSaved: "sačuvano",
  statusRejected: "nije sačuvano",
  reasons: {
    both_different: "Oba odgovora priznata i različita",
    same_answer: "Isti odgovor",
    only_player_1: "Samo prvi igrač",
    only_player_2: "Samo drugi igrač",
    neither: "Nijedan odgovor nije priznat",
  },
  /**
   * Required by `Plan.md` §7 on the results screen. The English sentence is the
   * wording the plan fixes; the Serbian line above it is the one players read.
   */
  honorSystemSr:
    "U ovoj verziji proveravamo samo početno slovo. Za tačnost pojmova odgovorni su igrači.",
  honorSystemEn:
    "Answers are checked only for the selected starting letter in this Week 3 version. Players are responsible for semantic correctness.",
} as const;

/** Copy for accounts, profiles and saved history. */
export const AUTH_SR = {
  signInTitle: "Prijava",
  registerTitle: "Novi nalog",
  email: "Imejl",
  password: "Lozinka",
  passwordHint: "Najmanje 15 znakova.",
  displayName: "Ime u igri",
  signIn: "Prijavi se",
  register: "Napravi nalog",
  signOut: "Odjavi se",
  needAccount: "Nemaš nalog? Napravi ga.",
  haveAccount: "Već imaš nalog? Prijavi se.",
  playAsGuest: "Igraj kao gost, bez naloga",
  signedInAs: "Prijavljen/a kao",
  account: "Nalog",
  profile: "Profil",
  backToGame: "Nazad na igru",
  profileTitle: "Tvoj profil",
  games: "Partije",
  wins: "Pobede",
  totalPoints: "Ukupno poena",
  historyTitle: "Odigrane partije",
  noHistory: "Još nema sačuvanih partija. Odigraj rundu dok si prijavljen/a.",
  opponentLabel: "Protivnik",
  previousPage: "Prethodna strana",
  nextPage: "Sledeća strana",
  page: "Strana",
  outcomeWin: "pobeda",
  outcomeLoss: "poraz",
  outcomeDraw: "nerešeno",
  guestNote: "Kao gost igraš normalno, ali partija se ne pamti.",
  /** The bar needs a word, not the whole sentence. */
  guestShort: "Gost",
  theme: "Tema",
  themes: {
    system: "Kao sistem",
    light: "Svetla",
    dark: "Tamna",
  },
  /** Every code the account API can return, in words a player can act on. */
  errors: {
    INVALID_INPUT: "Proveri imejl i lozinku.",
    AUTH_FAILED: "Pogrešan imejl ili lozinka.",
    EMAIL_UNAVAILABLE: "Nalog sa ovim imejlom već postoji.",
    UNAUTHORIZED: "Prijavi se da bi video/la ovu stranu.",
    FORBIDDEN: "Zahtev je odbijen.",
    RATE_LIMITED: "Previše pokušaja. Sačekaj pa probaj ponovo.",
    INTERNAL: "Greška na serveru. Probaj ponovo.",
    NOT_FOUND: "Strana ne postoji.",
    NETWORK: "Nema veze sa serverom.",
  },
} as const;
